language: ruby
rvm:
- 2.0.0
script: /bin/bash cores_and_outflows/gh-publisher-scripts/gh-publisher.sh
before_install:
- yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
- sudo apt-get update -y
- sudo apt-get install -y
     inkscape
     texlive-fonts-recommended
     texlive-latex-extra
     texlive-latex-recommended
     texlive-xetex
- wget https://journals.aps.org/files/revtex/revtex4-1.zip
- unzip revtex4-1.zip
